services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=task_manager_db'
      - 'POSTGRES_PASSWORD=david.task'
      - 'POSTGRES_USER=david'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: